theme: jekyll-theme-cayman
title: Work In Progress

sitelink : https://benchalmers.github.io/pmskills/
bookslink : {{ site.sitelink }}
books:
  pmdr2:
    link: pmdr2
    name: The Product Managers Desk Reference - Second Edition
  hooked:
    link: hooked
    name: Hooked - How To Build Habit Forming Products
